export const dynamic = "force-dynamic"

import { readdirSync } from "fs"
import { join } from "path"
import type { Metadata } from "next"
import { Cormorant_Garamond } from "next/font/google"
import { prisma } from "@/lib/prisma"
import BookingForm from "./booking-form"

/**
 * Display face for this page only — the rest of the CRM keeps Inter. A serif at
 * light weights with open letter-spacing is what separates a luxury property
 * page from a SaaS landing page.
 */
const display = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-display",
  display: "swap",
})

/** Palette: warm ink, ivory, champagne. No emoji, no saturated accent. */
const INK = "#0C0B0A"
const INK_SOFT = "#17150F"
const IVORY = "#FAF8F4"
const GOLD = "#C5A572"

const serif = "var(--font-display), Georgia, serif"
/** Small-caps eyebrow used above every section heading. */
const EYEBROW = "text-[11px] font-medium uppercase tracking-[0.34em]"

const BASE = "https://www.catherinegomezrealtor.com"
const PAGE_URL = `${BASE}/house-of-wellness`
const IMG_DIR = "/house-of-wellness"
/** Photo for JSON-LD. The social card itself is generated by opengraph-image.tsx. */
const OG_IMAGE = `${BASE}${IMG_DIR}/hero-brickell.jpg`

const TITLE =
  "House of Wellness Brickell — Apartamentos en Miami desde $419,900 | Catherine Gomez"
const DESCRIPTION =
  "House of Wellness Brickell: 34 pisos y 656 residencias en el corazón de Brickell, Miami, con más de 22,000 pies² de amenidades de bienestar. Estudios desde $419,900 USD y 10% al contrato. Agenda tu cita con Catherine Gomez, en español."

export const metadata: Metadata = {
  // Without this, the generated social-card URL resolves against the request
  // origin (the Railway host), and Facebook would be handed a link that is not
  // the canonical www one.
  metadataBase: new URL(BASE),
  title: TITLE,
  description: DESCRIPTION,
  keywords: [
    "House of Wellness Brickell",
    "House of Wellness Miami",
    "apartamentos en Brickell",
    "preconstrucción Miami",
    "comprar apartamento en Miami",
    "invertir en Miami",
    "condominios Brickell Miami",
    "North Development Miami",
    "apartamentos en venta Miami en español",
    "plan de pagos preconstrucción Miami",
  ],
  alternates: { canonical: PAGE_URL },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: PAGE_URL,
    type: "website",
    siteName: "Catherine Gomez Realtor",
    locale: "es_US",
    // No `images` here on purpose: opengraph-image.tsx / twitter-image.tsx
    // generate the real 1200x630 card, and file-based metadata only takes over
    // when the config does not also set images.
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
}

/**
 * Official renderings live in public/house-of-wellness/. Drop more files in
 * and they show up in the gallery automatically — no code change needed.
 */
function renderings(): string[] {
  try {
    return readdirSync(join(process.cwd(), "public", "house-of-wellness"))
      .filter(f => /\.(jpe?g|png|webp|avif)$/i.test(f))
      .sort()
      .map(f => `${IMG_DIR}/${f}`)
  } catch {
    return []
  }
}

const FEATURED: Record<string, string> = {
  hero: `${IMG_DIR}/hero-brickell.jpg`,
  fachada: `${IMG_DIR}/fachada.jpg`,
  gimnasio: `${IMG_DIR}/gimnasio.jpg`,
  cocina: `${IMG_DIR}/cocina.jpg`,
  recamara: `${IMG_DIR}/recamara-vista.jpg`,
}

/**
 * Real alt text per rendering, keyed by filename. A file without an entry still
 * gets a sensible generic description, so dropping new renderings in never
 * leaves an image undescribed.
 */
const GALLERY_ALT: Record<string, string> = {
  "balcon-bahia.jpg": "Balcón de una residencia de House of Wellness Brickell con sillón, mesa y vista abierta a la bahía de Biscayne y al skyline de Miami",
  "fachada-noche.jpg": "La torre House of Wellness iluminada de noche sobre 152 SW 9th Street, con sus balcones ajardinados y los arcos de la azotea",
  "torre-dia.jpg": "Vista diurna de la torre House of Wellness entre los edificios de Brickell, con vegetación en cada balcón",
  "recamara-closets.jpg": "Recámara de House of Wellness Brickell con clósets de madera integrados de piso a techo, cabecera tapizada y salida al balcón",
  "spa-piscina.jpg": "Terraza de spa de House of Wellness Brickell al atardecer, con piscina, jacuzzi, camastros y acceso al sauna",
  "bano.jpg": "Baño de una residencia de House of Wellness Brickell en travertino, con espejo retroiluminado, mueble de madera y regadera tipo lluvia",
  "piscina-aerea.jpg": "Vista aérea de la piscina de House of Wellness Brickell, con camastros, cabañas de madera y palmeras alrededor",
}

const AMENITIES: { title: string; body: string }[] = [
  { title: "Gimnasio de última generación", body: "Equipo completo de fuerza y cardio, con entrenador personal disponible en el edificio." },
  { title: "Spa, sauna y hammam", body: "Circuito de spa completo para recuperarte sin salir de casa." },
  { title: "Cold plunge", body: "Baño de inmersión en frío, parte del circuito de recuperación y bienestar." },
  { title: "Yoga y meditación", body: "Estudios dedicados a yoga, respiración y meditación guiada." },
  { title: "Piscina en la azotea", body: "Piscina en el rooftop con solárium, cabañas y vista abierta a la bahía y al skyline." },
  { title: "Juice bar y nutrición", body: "Wellness bar con jugos, vitaminas IV y acompañamiento de nutricionista." },
]

const UNITS: { type: string; size: string; note: string }[] = [
  { type: "Estudio con balcón", size: "371 pies² (34 m²)", note: "La entrada al proyecto — desde $419,900 USD." },
  { type: "1 recámara", size: "Consultar plano disponible", note: "Ideal para rentar a ejecutivos de Brickell." },
  { type: "1 recámara · 1 baño", size: "Consultar plano disponible", note: "Distribución abierta con balcón." },
  { type: "2 recámaras", size: "620 pies² (58 m²)", note: "Para vivir, o para rentar con mayor ocupación." },
]

const PAYMENTS: { pct: string; when: string }[] = [
  { pct: "10%", when: "Al firmar el contrato — desde $41,990 USD" },
  { pct: "10%", when: "Durante 2026" },
  { pct: "10%", when: "Junio de 2027" },
  { pct: "10%", when: "Durante 2028" },
  { pct: "60%", when: "Al cierre, cuando se entrega el apartamento" },
]

// Visible Q&A. Answer engines (Google AI Overviews, ChatGPT, Perplexity) quote
// clear question → answer pairs, and it wins featured snippets. Mirrored below
// in the FAQPage JSON-LD.
const FAQS: { q: string; a: string }[] = [
  {
    q: "¿Dónde queda House of Wellness Brickell?",
    a: "En 152 SW 9th Street, Brickell, Miami, Florida — justo al lado de The Underline y a una cuadra de Brickell City Centre. Desde ahí tomas el tren que llega directo al aeropuerto de Miami.",
  },
  {
    q: "¿Cuánto cuesta un apartamento en House of Wellness?",
    a: "Los estudios comienzan en $419,900 USD. Los precios de 1 y 2 recámaras cambian según el piso, la vista y la disponibilidad del momento. Agenda una cita con Catherine Gomez y te envía la lista de precios vigente el mismo día.",
  },
  {
    q: "¿Cuál es el plan de pagos?",
    a: "10% al firmar el contrato (desde $41,990 USD), 10% durante 2026, 10% en junio de 2027, 10% durante 2028 y el 60% restante al cierre, cuando te entregan el apartamento. No pagas todo de una vez: pagas por etapas mientras se construye.",
  },
  {
    q: "¿Puedo comprar si no soy residente ni ciudadano de Estados Unidos?",
    a: "Sí. Un extranjero puede comprar propiedad en Miami a su nombre o a través de una empresa (LLC), sin necesidad de residencia ni de historial de crédito estadounidense. También existen préstamos para extranjeros (foreign national loans) con aproximadamente 30% a 40% de enganche.",
  },
  {
    q: "¿Puedo rentar mi apartamento por Airbnb?",
    a: "El edificio permite renta con un mínimo de 15 días. No hay programa de administración obligatorio: puedes rentar por tu cuenta, con quien tú elijas, o no rentar.",
  },
  {
    q: "¿Puedo vivir yo en el apartamento o quedarme cuando quiera?",
    a: "Sí. No hay límite de días para que el dueño se quede. Puedes vivir en él todo el año, usarlo cuando viajes a Miami, o rentarlo el resto del tiempo.",
  },
  {
    q: "¿Qué amenidades tiene el edificio?",
    a: "Más de 22,000 pies² dedicados a bienestar: gimnasio de última generación, spa con sauna y hammam, cold plunge, estudios de yoga y meditación, piscina en la azotea con vista a la bahía, juice bar con vitaminas IV, nutricionista y entrenador personal. También tiene administración on-site y cinco niveles de estacionamiento.",
  },
  {
    q: "¿Cuánto son los gastos mensuales?",
    a: "El HOA (mantenimiento) está estimado en $1.70 por pie² al mes y los impuestos de propiedad en aproximadamente 1.8% del valor al año. En un estudio de 371 pies², el HOA ronda los $630 mensuales. Catherine te arma el cálculo completo de tu unidad.",
  },
  {
    q: "¿Las unidades se entregan amuebladas?",
    a: "No. Las unidades no se entregan amuebladas. Catherine te puede conectar con proveedores de mobiliario en Miami si piensas rentar el apartamento apenas lo recibas.",
  },
  {
    q: "¿Cuándo se entrega el edificio?",
    a: "El desarrollador confirma la fecha de entrega vigente al momento de la reserva, y queda por escrito en tu contrato. Pregúntale a Catherine en tu cita y te da la fecha que el desarrollador tiene confirmada hoy.",
  },
  {
    q: "¿Quién construye House of Wellness?",
    a: "North Development, una alianza de Oak Capital y Edifica, con más de 40 años de trayectoria en desarrollo inmobiliario.",
  },
  {
    q: "¿Cómo agendo una cita con Catherine Gomez?",
    a: "Elige el día y la hora que te sirvan en el calendario de esta misma página. La cita queda confirmada de inmediato y recibes el correo de confirmación. Catherine te atiende en español o en inglés, por teléfono o por Zoom.",
  },
]

export default async function HouseOfWellnessPage() {
  const config = await prisma.aIConfig.findFirst().catch(() => null)
  const agentName = config?.realtorName || "Catherine Gomez"
  const phone = config?.realtorPhone || ""
  const waDigits = phone.replace(/\D/g, "")
  const waUrl = waDigits
    ? `https://wa.me/${waDigits}?text=${encodeURIComponent(
        "Hola Catherine, vi la página de House of Wellness Brickell y quiero más información.",
      )}`
    : null

  const all = renderings()
  const featuredSet = new Set(Object.values(FEATURED))
  const gallery = all.filter(src => !featuredSet.has(src))
  const hero = all.includes(FEATURED.hero) ? FEATURED.hero : all[0]

  // Structured data — Google rich results and AI answer engines (AIO) read this.
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "RealEstateAgent",
        "@id": `${BASE}#agent`,
        name: agentName,
        url: BASE,
        ...(phone ? { telephone: phone } : {}),
        areaServed: "Miami, Florida, USA",
        knowsLanguage: ["es", "en"],
      },
      {
        "@type": "Residence",
        name: "House of Wellness Brickell",
        url: PAGE_URL,
        image: all.map(src => `${BASE}${src}`),
        description: DESCRIPTION,
        numberOfRooms: 656,
        address: {
          "@type": "PostalAddress",
          streetAddress: "152 SW 9th Street",
          addressLocality: "Miami",
          addressRegion: "FL",
          postalCode: "33130",
          addressCountry: "US",
        },
        amenityFeature: AMENITIES.map(a => ({
          "@type": "LocationFeatureSpecification",
          name: a.title,
          value: true,
        })),
      },
      {
        "@type": "Offer",
        name: "House of Wellness Brickell — estudios",
        url: PAGE_URL,
        price: 419900,
        priceCurrency: "USD",
        availability: "https://schema.org/PreOrder",
        seller: { "@id": `${BASE}#agent` },
      },
      {
        "@type": "ItemList",
        name: "Tipos de residencia en House of Wellness Brickell",
        itemListElement: UNITS.map((u, i) => ({
          "@type": "ListItem",
          position: i + 1,
          name: u.type,
          description: `${u.size}. ${u.note}`,
        })),
      },
      {
        "@type": "FAQPage",
        mainEntity: FAQS.map(f => ({
          "@type": "Question",
          name: f.q,
          acceptedAnswer: { "@type": "Answer", text: f.a },
        })),
      },
    ],
  }

  return (
    <main className={`${display.variable} min-h-screen bg-[#FAF8F4] text-[#0C0B0A]`}>
      {/* eslint-disable-next-line react/no-danger */}
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      {/* ---------------------------------------------------------- Hero */}
      <section className="relative flex min-h-[88vh] items-end">
        {hero && (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={hero}
            alt="House of Wellness Brickell: terraza en la azotea con piscina y vista al skyline de Miami al atardecer"
            className="absolute inset-0 h-full w-full object-cover"
          />
        )}
        <div
          className="absolute inset-0"
          style={{ background: "linear-gradient(to top, rgba(12,11,10,.93) 0%, rgba(12,11,10,.6) 26%, rgba(12,11,10,.12) 62%, rgba(12,11,10,0) 100%)" }}
        />
        <div
          className="absolute inset-0"
          style={{ background: "linear-gradient(to right, rgba(12,11,10,.72) 0%, rgba(12,11,10,.28) 48%, rgba(12,11,10,0) 78%)" }}
        />
        <div className="relative mx-auto w-full max-w-6xl px-6 pb-20 pt-32 text-white sm:pb-28">
          <p className={`${EYEBROW}`} style={{ color: GOLD }}>Brickell · Miami, Florida</p>

          <h1
            className="mt-7 max-w-3xl text-[2.9rem] font-light leading-[1.02] sm:text-[5.2rem]"
            style={{ fontFamily: serif }}
          >
            House of Wellness
          </h1>
          <div className="mt-7 h-px w-20" style={{ background: GOLD }} />
          <p
            className="mt-7 max-w-xl text-xl font-light leading-relaxed text-white/80 sm:text-2xl"
            style={{ fontFamily: serif }}
          >
            34 pisos y 656 residencias en el corazón de Brickell, con más de 22,000 pies²
            dedicados al bienestar.
          </p>

          <div className="mt-10 flex flex-wrap gap-x-14 gap-y-6">
            {[
              ["Estudios desde", "$419,900"],
              ["10% al contrato, desde", "$41,990"],
            ].map(([label, value]) => (
              <div key={label}>
                <p className={`${EYEBROW} text-white/50`}>{label}</p>
                <p className="mt-2 text-4xl font-light sm:text-5xl" style={{ fontFamily: serif }}>
                  {value} <span className="text-sm tracking-widest text-white/50">USD</span>
                </p>
              </div>
            ))}
          </div>

          <div className="mt-11 flex flex-wrap gap-4">
            <a
              href="#agendar"
              className="px-9 py-4 text-[13px] font-medium uppercase tracking-[0.18em] transition hover:brightness-110"
              style={{ background: GOLD, color: INK }}
            >
              Agendar cita con {agentName.split(" ")[0]}
            </a>
            {waUrl && (
              <a
                href={waUrl}
                className="border px-9 py-4 text-[13px] font-medium uppercase tracking-[0.18em] text-white transition hover:bg-white/10"
                style={{ borderColor: "rgba(255,255,255,.3)" }}
              >
                WhatsApp
              </a>
            )}
            <a
              href="#residencias"
              className="border px-9 py-4 text-[13px] font-medium uppercase tracking-[0.18em] text-white transition hover:bg-white/10"
              style={{ borderColor: "rgba(255,255,255,.3)" }}
            >
              Ver las residencias
            </a>
          </div>
        </div>
      </section>

      {/* -------------------------------------------------- Facts strip */}
      <section aria-label="Datos del proyecto" style={{ background: INK }}>
        <div className="mx-auto grid max-w-6xl grid-cols-2 gap-10 px-6 py-14 sm:grid-cols-4">
          {[
            ["34", "pisos"],
            ["656", "residencias"],
            ["22,000+", "pies² de bienestar"],
            ["5", "niveles de estacionamiento"],
          ].map(([n, l]) => (
            <div key={l} className="text-center">
              <p className="text-4xl font-light sm:text-5xl" style={{ fontFamily: serif, color: GOLD }}>{n}</p>
              <p className={`mt-3 ${EYEBROW} text-white/45`}>{l}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ------------------------------------------------- The concept */}
      <section className="mx-auto max-w-6xl px-5 py-20">
        <div className="grid items-center gap-16 lg:grid-cols-2">
          <div>
            <p className={EYEBROW} style={{ color: GOLD }}>El concepto</p>
            <h2 className="mt-6 text-[2.1rem] font-light leading-[1.12] sm:text-[3rem]" style={{ fontFamily: serif }}>
              No es un edificio con gimnasio.<br />
              Es un edificio construido alrededor de tu bienestar.
            </h2>
            <p className="mt-8 text-lg leading-relaxed text-[#57514A]">
              La mayoría de las torres de Brickell dedican un piso a las amenidades. House of
              Wellness dedica más de 22,000 pies² — un circuito completo de spa, movimiento,
              recuperación y nutrición que usas todos los días sin salir de tu casa.
            </p>
            <p className="mt-5 text-lg leading-relaxed text-[#57514A]">
              Y está donde quieres estar: a una cuadra de Brickell City Centre, junto a
              The Underline, y sobre la línea de tren que te deja en el aeropuerto de Miami.
            </p>
          </div>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={FEATURED.fachada}
            alt="Fachada iluminada de la torre House of Wellness en Brickell, Miami, con balcones ajardinados"
            className="w-full object-cover"
          />
        </div>
      </section>

      {/* ---------------------------------------------------- Amenities */}
      <section id="amenidades" className="py-24 text-white" style={{ background: INK }}>
        <div className="mx-auto max-w-6xl px-6">
          <p className={EYEBROW} style={{ color: GOLD }}>Amenidades</p>
          <h2 className="mt-6 max-w-2xl text-[2.1rem] font-light leading-[1.12] sm:text-[3rem]" style={{ fontFamily: serif }}>
            Más de 22,000 pies² pensados para cómo quieres vivir
          </h2>
          <div className="mt-16 grid gap-x-14 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">
            {AMENITIES.map((a, i) => (
              <div key={a.title} className="border-t pt-6" style={{ borderColor: "rgba(197,165,114,.28)" }}>
                <p className="text-sm tracking-[0.2em]" style={{ color: GOLD, fontFamily: serif }} aria-hidden="true">
                  {String(i + 1).padStart(2, "0")}
                </p>
                <h3 className="mt-4 text-2xl font-light" style={{ fontFamily: serif }}>{a.title}</h3>
                <p className="mt-3 leading-relaxed text-white/55">{a.body}</p>
              </div>
            ))}
          </div>
          <div className="mt-20 grid gap-6 sm:grid-cols-2">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={FEATURED.gimnasio}
              alt="Gimnasio de House of Wellness Brickell con equipo de fuerza y cardio y ventanales de piso a techo"
              className="h-80 w-full object-cover"
            />
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={FEATURED.cocina}
              alt="Cocina de una residencia de House of Wellness Brickell con acabados en madera clara y electrodomésticos integrados"
              className="h-80 w-full object-cover"
            />
          </div>
        </div>
      </section>

      {/* --------------------------------------------------- Residences */}
      <section id="residencias" className="mx-auto max-w-6xl px-5 py-20">
        <p className={EYEBROW} style={{ color: GOLD }}>Las residencias</p>
        <h2 className="mt-6 text-[2.1rem] font-light leading-[1.12] sm:text-[3rem]" style={{ fontFamily: serif }}>
          Desde estudios hasta 2 recámaras
        </h2>
        <div className="mt-12 grid items-start gap-14 lg:grid-cols-2">
          <div className="border-t" style={{ borderColor: "rgba(12,11,10,.14)" }}>
            <table className="w-full text-left">
              <caption className="sr-only">Tipos de residencia disponibles en House of Wellness Brickell</caption>
              <thead className={`${EYEBROW} text-[#8A8178]`}>
                <tr>
                  <th scope="col" className="py-4 pr-4 font-medium">Tipo</th>
                  <th scope="col" className="py-4 font-medium">Tamaño</th>
                </tr>
              </thead>
              <tbody>
                {UNITS.map(u => (
                  <tr key={u.type} className="border-t" style={{ borderColor: "rgba(12,11,10,.09)" }}>
                    <th scope="row" className="py-6 pr-4 text-left align-top">
                      <span className="block text-xl font-light" style={{ fontFamily: serif }}>{u.type}</span>
                      <span className="mt-2 block text-sm font-normal leading-relaxed text-[#7A736A]">{u.note}</span>
                    </th>
                    <td className="whitespace-nowrap py-6 align-top text-[#57514A]">{u.size}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            <p className="border-t py-6 text-sm leading-relaxed text-[#7A736A]" style={{ borderColor: "rgba(12,11,10,.14)" }}>
              Los precios de 1 y 2 recámaras cambian según el piso, la vista y la disponibilidad.{" "}
              <a href="#agendar" className="underline underline-offset-4" style={{ color: "#8A6D32" }}>
                Agenda tu cita
              </a>{" "}
              y {agentName.split(" ")[0]} te manda la lista vigente el mismo día. Las unidades no se
              entregan amuebladas.
            </p>
          </div>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={FEATURED.recamara}
            alt="Recámara de una residencia de House of Wellness Brickell con clósets de madera integrados y ventanal con vista a la bahía"
            className="w-full object-cover"
          />
        </div>
      </section>

      {/* ------------------------------------------------- Payment plan */}
      <section id="plan-de-pagos" className="py-24" style={{ background: "#F2EDE4" }}>
        <div className="mx-auto max-w-6xl px-6">
          <p className={EYEBROW} style={{ color: "#8A6D32" }}>Plan de pagos</p>
          <h2 className="mt-6 text-[2.1rem] font-light leading-[1.12] sm:text-[3rem]" style={{ fontFamily: serif }}>
            No pagas todo de una vez. Pagas mientras se construye.
          </h2>
          <ol className="mt-14 grid gap-x-8 gap-y-10 sm:grid-cols-5">
            {PAYMENTS.map((p, i) => (
              <li key={p.when} className="border-t pt-5" style={{ borderColor: "rgba(12,11,10,.18)" }}>
                <p className={`${EYEBROW} text-[#8A8178]`}>Pago {i + 1}</p>
                <p className="mt-3 text-4xl font-light" style={{ fontFamily: serif, color: "#8A6D32" }}>{p.pct}</p>
                <p className="mt-3 text-sm leading-relaxed text-[#57514A]">{p.when}</p>
              </li>
            ))}
          </ol>
          <div className="mt-16 grid gap-10 sm:grid-cols-3">
            {[
              ["Renta mínima de 15 días", "Puedes rentar tu apartamento, sin programa de administración obligatorio."],
              ["Sin límite para el dueño", "Quédate los días que quieras, o vive ahí todo el año."],
              ["Gastos estimados", "HOA de $1.70 por pie² al mes e impuestos de aproximadamente 1.8% anual."],
            ].map(([t, b]) => (
              <div key={t} className="border-t pt-5" style={{ borderColor: "rgba(12,11,10,.18)" }}>
                <h3 className="text-xl font-light" style={{ fontFamily: serif }}>{t}</h3>
                <p className="mt-3 text-sm leading-relaxed text-[#57514A]">{b}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ----------------------------------------------------- Location */}
      <section id="ubicacion" className="mx-auto max-w-6xl px-5 py-20">
        <p className={EYEBROW} style={{ color: GOLD }}>Ubicación</p>
        <h2 className="mt-6 text-[2.1rem] font-light leading-[1.12] sm:text-[3rem]" style={{ fontFamily: serif }}>
          152 SW 9th Street, Brickell
        </h2>
        <div className="mt-12 grid gap-14 lg:grid-cols-2">
          <ul className="space-y-8">
            {[
              ["Junto a The Underline", "El parque lineal de Miami, con ciclovía y senderos, empieza en tu puerta."],
              ["A una cuadra de Brickell City Centre", "Tiendas, restaurantes y cine, caminando."],
              ["Tren directo al aeropuerto", "La estación del Metrorail te deja en el Aeropuerto Internacional de Miami sin cambiar de tren."],
              ["El distrito financiero de Miami", "Donde trabajan los inquilinos que rentan: banca, tecnología y fondos de inversión."],
            ].map(([t, b]) => (
              <li key={t} className="border-t pt-5" style={{ borderColor: "rgba(12,11,10,.14)" }}>
                <strong className="block text-xl font-light" style={{ fontFamily: serif }}>{t}</strong>
                <span className="mt-2 block leading-relaxed text-[#57514A]">{b}</span>
              </li>
            ))}
          </ul>
          <iframe
            title="Mapa de la ubicación de House of Wellness en 152 SW 9th Street, Brickell, Miami"
            src="https://www.google.com/maps?q=152+SW+9th+St,+Miami,+FL+33130&output=embed"
            className="h-[26rem] w-full border"
            style={{ borderColor: "rgba(12,11,10,.14)" }}
            loading="lazy"
            referrerPolicy="no-referrer-when-downgrade"
          />
        </div>
      </section>

      {/* ------------------------------------------------------ Gallery */}
      {gallery.length > 0 && (
        <section id="galeria" className="py-24" style={{ background: "#F2EDE4" }}>
          <div className="mx-auto max-w-6xl px-6">
            <p className={EYEBROW} style={{ color: "#8A6D32" }}>Galería</p>
            <h2 className="mt-6 text-[2.1rem] font-light sm:text-[3rem]" style={{ fontFamily: serif }}>Así se va a ver</h2>
            <div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {gallery.map(src => (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  key={src}
                  src={src}
                  alt={GALLERY_ALT[src.split("/").pop() || ""] || "Render del proyecto House of Wellness Brickell en Miami"}
                  loading="lazy"
                  className="h-72 w-full object-cover"
                />
              ))}
            </div>
            <p className="mt-8 text-xs text-[#9A9289]">
              Imágenes conceptuales del desarrollador. Los acabados y las vistas pueden variar.
            </p>
          </div>
        </section>
      )}

      {/* ------------------------------------------------------ Booking */}
      <section id="agendar" className="py-24 text-white" style={{ background: INK_SOFT }}>
        <div className="mx-auto max-w-6xl px-6">
          <div className="grid gap-16 lg:grid-cols-[1fr_1.1fr]">
            <div>
              <p className={EYEBROW} style={{ color: GOLD }}>Tu cita</p>
              <h2 className="mt-6 text-[2.1rem] font-light leading-[1.12] sm:text-[3rem]" style={{ fontFamily: serif }}>
                Habla con {agentName}
              </h2>
              <p className="mt-8 text-lg leading-relaxed text-white/60">
                Elige el día y la hora que te sirvan. Tu cita queda confirmada al instante
                y te llega el correo de confirmación.
              </p>
              <ul className="mt-10 space-y-5 text-white/60">
                {[
                  "La lista de precios vigente y los planos disponibles",
                  "El cálculo real de tu pago inicial y de los gastos mensuales",
                  "Cómo comprar desde fuera de Estados Unidos, paso a paso",
                  "Qué unidades quedan y cuáles rentan mejor",
                ].map(t => (
                  <li key={t} className="flex gap-4">
                    <span className="mt-2.5 h-px w-5 shrink-0" style={{ background: GOLD }} aria-hidden="true" />
                    <span>{t}</span>
                  </li>
                ))}
              </ul>
              <p className="mt-10 text-sm text-white/40">
                Atención en español e inglés.{" "}
                {phone && <>También puedes llamar al <a href={`tel:${phone}`} className="underline">{phone}</a>.</>}
              </p>
            </div>
            <div className="text-[#0C0B0A]">
              <BookingForm />
            </div>
          </div>
        </div>
      </section>

      {/* ---------------------------------------------------------- FAQ */}
      <section id="preguntas" className="mx-auto max-w-4xl px-5 py-20">
        <p className={EYEBROW} style={{ color: GOLD }}>Preguntas frecuentes</p>
        <h2 className="mt-6 text-[2.1rem] font-light leading-[1.12] sm:text-[3rem]" style={{ fontFamily: serif }}>
          Lo que todo el mundo pregunta primero
        </h2>
        <div className="mt-12">
          {FAQS.map(f => (
            <details key={f.q} className="group border-t py-6" style={{ borderColor: "rgba(12,11,10,.14)" }}>
              <summary className="flex cursor-pointer list-none items-start justify-between gap-6 text-left">
                <h3 className="text-xl font-light leading-snug" style={{ fontFamily: serif }}>{f.q}</h3>
                <span
                  className="mt-1 shrink-0 text-lg font-light transition group-open:rotate-45"
                  style={{ color: GOLD }}
                  aria-hidden="true"
                >
                  +
                </span>
              </summary>
              <p className="mt-4 max-w-3xl leading-relaxed text-[#57514A]">{f.a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* ------------------------------------------------- Closing CTA */}
      <section className="py-24 text-center text-white" style={{ background: INK }}>
        <div className="mx-auto max-w-3xl px-6">
          <h2 className="text-[2.1rem] font-light leading-[1.12] sm:text-[3rem]" style={{ fontFamily: serif }}>
            Los estudios empiezan en $419,900
          </h2>
          <p className="mt-6 text-lg leading-relaxed text-white/55">
            Y la reserva, en $41,990. Agenda tu cita y {agentName.split(" ")[0]} te explica los números de tu caso.
          </p>
          <div className="mt-11 flex flex-wrap justify-center gap-4">
            <a
              href="#agendar"
              className="px-9 py-4 text-[13px] font-medium uppercase tracking-[0.18em] transition hover:brightness-110"
              style={{ background: GOLD, color: INK }}
            >
              Agendar mi cita
            </a>
            {waUrl && (
              <a
                href={waUrl}
                className="border px-9 py-4 text-[13px] font-medium uppercase tracking-[0.18em] transition hover:bg-white/10"
                style={{ borderColor: "rgba(255,255,255,.3)" }}
              >
                WhatsApp
              </a>
            )}
          </div>
        </div>
      </section>

      <footer className="py-12 text-center text-sm" style={{ background: INK, color: "rgba(255,255,255,.45)" }}>
        <p className={EYEBROW}>{agentName} · Bienes raíces en Miami, Florida</p>
        <p className="mx-auto mt-5 max-w-2xl px-6 text-xs leading-relaxed text-white/25">
          House of Wellness es un proyecto de North Development (Oak Capital + Edifica). Las imágenes
          son renders conceptuales del desarrollador. Precios, planos, amenidades y fechas están
          sujetos a cambio sin previo aviso y se confirman por escrito en el contrato de compraventa.
        </p>
      </footer>
    </main>
  )
}
