-- CreateTable
CREATE TABLE "WebsiteConfig" (
    "id" TEXT NOT NULL,
    "heroTitle" TEXT NOT NULL DEFAULT 'Your Dream Home Awaits',
    "heroSubtitle" TEXT NOT NULL DEFAULT 'Luxury real estate with a personal touch',
    "heroImageUrl" TEXT,
    "heroCta" TEXT NOT NULL DEFAULT 'View Listings',
    "heroCta2" TEXT NOT NULL DEFAULT 'Contact Me',
    "agentName" TEXT NOT NULL DEFAULT 'Catherine Gomez',
    "agentTitle" TEXT NOT NULL DEFAULT 'Luxury Real Estate Specialist',
    "agentPhone" TEXT,
    "agentEmail" TEXT,
    "agentPhotoUrl" TEXT,
    "agentBio" TEXT NOT NULL DEFAULT 'With over 15 years of experience in Miami''s luxury real estate market, I bring unmatched expertise and dedication to every transaction.',
    "agentLicense" TEXT,
    "agentBrokerage" TEXT,
    "yearsFounded" INTEGER NOT NULL DEFAULT 2009,
    "homesSold" INTEGER NOT NULL DEFAULT 500,
    "satisfiedClients" INTEGER NOT NULL DEFAULT 98,
    "avgDaysOnMarket" INTEGER NOT NULL DEFAULT 21,
    "primaryColor" TEXT NOT NULL DEFAULT '#0e8fe9',
    "accentColor" TEXT NOT NULL DEFAULT '#c9a84c',
    "logoUrl" TEXT,
    "facebook" TEXT,
    "instagram" TEXT,
    "linkedin" TEXT,
    "youtube" TEXT,
    "aboutHeading" TEXT NOT NULL DEFAULT 'Why Work With Me',
    "testimonials" TEXT NOT NULL DEFAULT '[]',
    "serviceAreas" TEXT NOT NULL DEFAULT '[]',
    "videoUrl" TEXT,
    "metaTitle" TEXT,
    "metaDescription" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "WebsiteConfig_pkey" PRIMARY KEY ("id")
);
